### ISSUE TITLE
latest version of linter doesn't work

### ISSUE THREAD

**Issue by eddwardo** [AtomLinter/linter-elixirc#13]
Atom - 1.0.19
OS: Mac OS 10.11
atom linter - 1.8.1
atom linter-elixirrc - 0.2.2, default settings.

Linter does not raise any exceptions, it just doesn't work.

**Comment by steelbrain** [comment]
This package hasn't updated to the latest API yet. I would love to review a PR for this

**Comment by eddwardo** [comment]
I am not familiar with coffe script nor atom.io plugin system - is it feasible task for a beginner?

**Comment by steelbrain** [comment]
You can just drop all of the coffee code and rewrite it in pure javascript. https://github.com/steelbrain/Atom-Hack/blob/master/lib/main.js#L54-L97 <-- this could act as a reference.
If you are comfortable with javascript then we'd be more than happy to accept your contribution. Otherwise you'll have to wait till I am free to do it myself. It could take time but not more than a week

**Comment by remiq** [comment]
@eddwardo: Please check latest version of the plugin - 1.0.0
