### ISSUE TITLE
Linting only works for first added project.

### ISSUE THREAD

**Issue by hitoridewanai** [AtomLinter/linter-elixirc#20]
Hi. I have a couple of projects added like this:
<img width="200" alt="screen shot 2015-11-26 at 02 03 04" src="https://cloud.githubusercontent.com/assets/2444759/11412832/dcee599c-93e1-11e5-8f51-d25eac9498dd.png">

It seems that linting only works for the first of it. I've tried adding/removing/re-adding to no avail. This is not a path issue described widely on OS X as this seems to work fine when there is only one project added.

There are no errors on the dev console.

Thanks!

**Comment by Arcanemagus** [comment]
#58 should fix this, which was included in v1.1.6. Can you please try that version and see if you are still experiencing this issue?

**Comment by leefr** [comment]
I believe I am experiencing a similar/related issue.  Linting works only if I open the in the root folder of the project directly, but my usual way of working is to open the directory above all my git checkouts so that I can easily look at/edit on multiple repos at the same time (some are companion applications or libs for others).  It seems like the path you specify to find dependencies for elixirc (_build/dev/lib/*/ebin) is being not being resolved relative to the project base for the current .ex file.  It looks like you know this, based on the documentation, but it is a limitation that defeats much of the power/utility of Atom's project/file management bar.

A simple crawl up the directory tree until finding a mix.exs or reaching some (settable?) limit and caching the found base dir for a given file path should do the trick to make this usable.  You could also give the option to always use mix if you are locating the project dir.

As it is, I doubt I will have this linter enabled most of the time since I get an error on any 'require' statements that are for non-core modules.

**Comment by Arcanemagus** [comment]
A very simple workaround for this is to open each project as a project folder in Atom... however you can still get most of the same effect by adding _multiple projects_ to the same Atom window. This will allow the "Project" concept built into Atom to work it's magic and for each of these to work properly, but does require more setup on your part.

From what you are describing for some projects there could be a fallback method available from searching for specific files, @remiq would have to be the one to speak to that though as I don't use this linter (or the Elixir language) myself.

**Comment by leefr** [comment]
Thanks for the tip!

I guess what I am looking for is a bit more awareness about the standard Elixir project structure so that I don't have to worry about how I opened a file/project and having to open other files/dependencies that should normally just be found based on relative locations, standard directory names, (lib, deps, etc.) and known project file name (mix.exs).

The Go linters seem to do this pretty well, though I do admit they have a slightly more rigid structure that facilitates this for Go itself as well as any linters.

**Comment by Arcanemagus** [comment]
I believe this is fixed in #82, I'll be pushing out a release including that soon.
